### PR TITLE
CaseStudy hero #20

### PR DESCRIPTION
**Pull request by saugatmalla**
Casestudy Hero block used in Work page

Fix [#20](https://github.com/solomon71/tbx-olympus/issues/20)

Test URLs:
- Before: https://main--tbx-olympus--solomon71.hlx.page/drafts/saugat/casestudy-hero
- After: https://casestudy-hero--tbx-olympus--solomon71.hlx.page/drafts/saugat/casestudy-hero

### CODE REVIEW

**Comment by solomon71** [comment]
Hey @saugatmalla - see this feedback concerning revealing ~5% at bottom of viewport. https://www.loom.com/share/247f669f19fd4f45ad585f7a22b7cc82

**Comment by saugatmalla** [comment]
> Hey @saugatmalla - see this feedback concerning revealing ~5% at bottom of viewport. https://www.loom.com/share/247f669f19fd4f45ad585f7a22b7cc82

Hey @solomon71, I have kept some space at the bottom, using `90vh` value, let me know if we need to change that value.

**Comment by solomon71** [comment]
@saugatmalla - thx. Let's go with 95vh

**Review by snowiewdev — APPROVED** [review]

**Comment by solomon71** [comment]
Approved

**Pull request merged**
